<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
  * @package  Ced_GShop
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */
 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$json = json_encode($objectManager->create('Ced\GShop\Model\Source\Profile\Category\Rootlevel')->toOptionArray());
$level_1 = $block->getLevel( 1 );
?>

<script>
    require([
        "jquery",
        "jquery/ui"
    ], function($){

        var json = <?php echo $json; ?>;
        var level_1=<?php echo json_encode($level_1);?>;

        $( "#automplete-2" ).autocomplete({
            source: json,
            autoFocus:true
        });
        $('#ui-id-1').on('click', function() {
            $("#level_0").val($("#automplete-2").val());
            $("#automplete-2").val($("#level_0 option:selected").text());
            $(".ui-helper-hidden-accessible").hide();
            $('[name="level_1"]').empty();
            $('[name="level_1"]').removeAttr('disabled');
            $('[name="level_2"]').empty();
            $('[name="level_2"]').prepend('<option value="">Please select level 2 category</option>');
            $('[name="level_2"]').attr('disabled', 'disabled');
            $('[name="level_3"]').empty();
            $('[name="level_3"]').prepend('<option value="">Please select level 3 category</option>');
            $('[name="level_3"]').attr('disabled', 'disabled');
            $('[name="level_4"]').empty();
            $('[name="level_4"]').prepend('<option value="">Please select level 4 category</option>');
            $('[name="level_4"]').attr('disabled', 'disabled');
            $('[name="level_5"]').empty();
            $('[name="level_5"]').prepend('<option value="">Please select level 5 category</option>');
            $('[name="level_5"]').attr('disabled', 'disabled');
            $('[name="level_6"]').empty();
            $('[name="level_6"]').prepend('<option value="">Please select level 6 category</option>');
            $('[name="level_6"]').attr('disabled', 'disabled');
            var cat_id=$('[name="level_0"]').val();
            for (var key in level_1) {
                for (var subkey in level_1[key]){
                    if((subkey == 'csv_firstlevel_id') && (level_1[key][subkey] == cat_id)){
                        leaf = false;
                        $('[name="level_1"]').append('<option value="'+level_1[key]['csv_secondlevel_id']+'">'+level_1[key]['csv_secondlevel_id']+'</option>');
                    }
                }
            }
        });

        $("#automplete-2").keyup(function(){
            if(this.value == '')
                $(".ui-helper-hidden-accessible").hide();
            else
                $(".ui-helper-hidden-accessible").show();

        });
    });
</script>
<style>
        .ui-widget {
            font-family: Trebuchet MS,Tahoma,Verdana,Arial,sans-serif;
            font-size: 1.1em;
        }
        .ui-menu {
            display: block;
            list-style: outside none none;
            margin: 0;
            outline: medium none;
            padding: 2px;
        }
        .ui-autocomplete {
            cursor: default;
            left: 0;
            position: absolute;
            top: 0;
        }
        .ui-menu .ui-menu-item a {
            display: block;
            font-weight: normal;
            line-height: 1.5;
            min-height: 0;
            padding: 2px 0.4em;
            text-decoration: none;
        }
        .ui-widget-content a {
            color: #333333;
        }
        .ui-autocomplete .ui-state-focus {
            border: 1px solid #fbcb09;
            background: #fdf5ce url('images/ui-bg_glass_100_fdf5ce_1x400.png') 50% 50% repeat-x;
            font-weight: bold;
            color: #c77405;
        }
        .ui-autocomplete {
            background: #eeeeee url("images/ui-bg_highlight-soft_100_eeeeee_1x100.png") repeat-x scroll 50% top;
            border: 1px solid #dddddd;
            color: #333333;
            height: 300px;
            width: 100px;
            overflow: scroll;
        }
</style>
